### ISSUE TITLE
Security? 

### ISSUE THREAD

**Issue by Levi-Lesches** [mrd0x/BITB#4]
When I read an article about this I thought this was a proof of concept showing how such an attack could happen, and that we should be careful. But what's the point of offering it as an easily accessible repository, even going so far as to add more features like delayed loading to make it more realistic? Are you _trying_ to promote phishing? There's a lot of wiggle room between exposing a potential attack vector and promoting its use. This just looks like the latter.

**Comment by mrd0x** [comment]
You do understand it's basic HTML/CSS/JavaScript? Whether I publish these templates or not anyone can easily replicate these templates from scratch in under 30 minutes.

It is true that originally they were intended to be PoCs, since then I've received requests to update them by fellow red teamers and penetration testers and therefore decided to change my approach.

This repository will continue to be updated for use by red teamers and penetration testers. If you're worried it might be abused please learn how to detect this phishing attack.

**Comment by Levi-Lesches** [comment]
> If you're worried it might be abused please learn how to detect this phishing attack.

The demo seems to imply that this method of opening fake windows is indistinguishable from real windows. For example, I thought moving the fake window around would surely break it, but the gif seems to show otherwise. Perhaps you can include some tips in the README or some other doc on what weaknesses this particular method has that allows it to be identified. (Eg, does it appear in the taskbar?) Just looking for ways to make this repo more useful to innocent users than attackers.
